### ISSUE TITLE
test the model

### ISSUE THREAD

**Issue by happybcloud** [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch#1]
Thank you very much for your code!
Using the train.py, we can train our own model.  We are looking forward to your upload of the test code.

**Comment by junyuchen245** [comment]
Hi,

You can use infer.py to test your model.

Thanks,
Junyu

**Comment by happybcloud** [comment]
@junyuchen245 
Thank you very much for your reply! I am looking forward to evaluating your method on my dataset.
Jowing

**Comment by junyuchen245** [comment]
No problem. Please let me know if you have any further questions.

Junyu
