### ISSUE TITLE
How do you setting your data in order to run python train.py?

### ISSUE THREAD

**Issue by tphankr** [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch#2]
Please help me setting the data in order to train. Or help me have the simply data to train ( I also download your datas that mentioned but I can not use it)
![image](https://user-images.githubusercontent.com/37217354/123908635-c79f2a80-d945-11eb-8b6f-e9845db4f1f0.png)
I assumer use the BraTS_2018 dataset. It looks like: 
![image](https://user-images.githubusercontent.com/37217354/123909967-cb33b100-d947-11eb-9ff5-75b4c2e1dc0f.png)
![image](https://user-images.githubusercontent.com/37217354/123909031-6fb4f380-d946-11eb-84e0-dcb30ff3c44f.png)

Val:
![image](https://user-images.githubusercontent.com/37217354/123910028-e1417180-d947-11eb-9f4a-5f0b49187969.png)
![image](https://user-images.githubusercontent.com/37217354/123910083-f28a7e00-d947-11eb-9655-9ba5806d1918.png)

When I set the above path, the following error occurs:
![image](https://user-images.githubusercontent.com/37217354/123909339-dc2ff280-d946-11eb-8858-93538e09f3f6.png)

Thank you, very much.

**Comment by junyuchen245** [comment]
Hi,

The script assumes the images are preprocessed (e.g., intensity normalized into a range of [0,1], skull stripped, and affine registered) and in .pkl format. A single .pkl file consists of one input image and one ground truth. You can find out details about this in ["datasets.py"](https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/main/ViT-V-Net/data/datasets.py).

For Brats, you can follow the preprocessing steps [here](https://github.com/China-LiuXiaopeng/BraTS-DMFNet). However, they normalized images to z-scores. I haven't tested if the model can work with negative values, so it is better to normalize the images into [0,1].

For other public MRI datasets, you will need to do the preprocessing yourself by using [FreeSurfer](https://surfer.nmr.mgh.harvard.edu/). I've listed some of the commands I used [here](https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/main/PreprocessingMRI.md).

Thanks,
Junyu

**Comment by tphankr** [comment]
I am following your advise. I try to do succesully this task. thank you.
