### ISSUE TITLE
The process of making data

### ISSUE THREAD

**Issue by wenqian11** [junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch#5]
Hi！
I'm sorry to bother you.
I followed your suggestion to convert the file to pkl format, but it still doesn't work properly. Could you please help me see where I went wrong?
![image](https://user-images.githubusercontent.com/103731366/163916361-4c3e8564-e3c9-4b64-b859-d5da3ab81a6e.png)
![image](https://user-images.githubusercontent.com/103731366/163916542-64dc89a3-ad5d-4396-bf4c-2c765ea4a026.png)
Train
![image](https://user-images.githubusercontent.com/103731366/163916586-b0316f78-747d-4316-91d6-6b1157d1d040.png)
Val
![image](https://user-images.githubusercontent.com/103731366/163916609-4903b61f-cd15-40aa-8436-c7ab4e46e060.png)
Very grateful for your help

**Comment by junyuchen245** [comment]
Hi @wenqian11 ,

To make it compatible with your own dataset, you will need to modify the dataset function here:
https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/8f4ac9256f76b2e4e9c4920a1b1d23b1187f74de/ViT-V-Net/data/datasets.py#L10

Btw, you won't need to use .pkl file format if you have your own dataset function. Please check out this tutorial:
https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

Junyu

**Comment by wenqian11** [comment]
Thanks a lot for your help. I am trying to run this task successfully following your suggestion.
